### ISSUE TITLE
Itinerary Components Implementation

### ISSUE THREAD

**Issue by cpilande** [heyitsmass/BayView#61]
**Description**
This issue tracks the implementation of the initial version of the Itinerary Components based on the Figma Mockup. These consist of any components that are related to the creation of the itinerary that will be viewed by the user. 

**Open Questions**

**Tasks**
- [ ] -  Implement the Title Card component.
- [ ] -  Implement the Event component.
- [ ] -  Implement the Full Itinerary component.
- [ ] -  Create a sample itinerary to receive feedback on changes to the visual design.
- [ ] -  Write tests to verify the components' functionality.

Related Issues and PRs

- https://github.com/heyitsmass/BayView/pull/62
